### ISSUE TITLE
Azide-alkyne Huisgen cycloaddition

### ISSUE THREAD

**Issue by peggjt** [JelfsMaterialsGroup/stk#6]
The Azide-alkyne Huisgen cycloaddition needs to be added to stk.
(https://en.wikipedia.org/wiki/Azide-alkyne_Huisgen_cycloaddition)

In the stk.molecular.functional_groups module:
- Alkynes are present.
- Azides need to be added.

The challenge is the formation of a new ring product. An option to control the position of the adduct is also desirable.

**Comment by fiszczyp** [comment]
I started some work on it some time ago but neglected in favour of simplifying the building blocks. Would be quite keen to get back to it, given that many rotaxanes we are interested in are based on this chemistry.

**Comment by pwvbutler** [comment]
I had a quick look at this, and I've implemented the Azide and AzideFactory classes you would need (see below). Unfortunately, implementing the reaction algorithm is a bit much for me at the moment, though I imagine dealing with the azide resonance forms would be a decent challenge.

If you're not using the reaction in the assembly of a topology, for example just generating building blocks, it’s simple to do the reaction in rdkit and then use the init_from_rdkit_mol function to get the stk building block. I'll attach an example below (it's a real doozy of a SMARTS pattern).

[stk_azide.zip](https://github.com/JelfsMaterialsGroup/stk/files/5521488/stk_azide.zip)
[rdkit_AAC.txt](https://github.com/JelfsMaterialsGroup/stk/files/5521489/rdkit_AAC.txt)

**Comment by lukasturcani** [comment]
This is awesome! Thank you very much for this! I will have a look at it this week.

**Comment by lukasturcani** [comment]
Oh and I'll close and transfer this issue to https://github.com/lukasturcani/stk/issues/254

As this repo is not used for development.
